--DROP SCHEMA IF EXISTS bank;

CREATE SCHEMA bank;

CREATE TABLE bank.users (
  ID BIGINT UNSIGNED NOT NULL,
  LOGIN VARCHAR(64) NOT NULL,
  PASSWORD VARCHAR(64) NOT NULL,
  FIRSTNAME VARCHAR(64),
  LASTNAME VARCHAR(64) );